### PR TITLE
Temporary workaround to fix audio output

### PR DESCRIPTION
**Pull request by secuflag**
* audio.primary.rpi3.so picked from AndroidThings Developer Preview 1

### CODE REVIEW

**Comment by secuflag** [comment]
@peyo-hd I'm not sure if you would like to merge this, anyway here it is, maybe could be helpful to other people.

**Comment by ikalkov** [comment]
@secuflag Sorry, I'll better ask here. Is this the only thing required to fix audio? Which one does it fix: HDMI or 3.5 audio jack?

**Comment by secuflag** [comment]
HDMI.
I'm not sure about the audio jack, not tested yet.

**Comment by 459below** [comment]
I just copied the library into the current RTAndroid nightly. I can confirm that it enables HDMI audio. Thanks a lot!

**Comment by ikalkov** [comment]
@secuflag, @459below: Thanks guys, we resolved the audio issue by fixing source code in other repositories. No need to use precompiled binaries.

**Pull request closed without merging**
