### PR TITLE
Various changes, mostly just cleaning up

### PR DESCRIPTION
**Pull request by KonstaT**

### CODE REVIEW

**Comment by ikalkov** [comment]
Looks good to me. I'd like to hear @peyo-hd's opinion before merge.

**Comment by peyo-hd** [comment]
Looks good to me removing legacy & unused Macros.
But let selectively merge the commits after checking it step by step.

**Comment by KonstaT** [comment]
Take your time to test things out. I did an AOSP android-7.1.2_r4 build yesterday and LineageOS 14.1 build last week with these changes (and more). Everything working as it should AFAICT.

**Comment by ric96** [comment]
@KonstaT Not to get too off topic, didn't​ lineage have an surface flinger crash issues?

**Comment by KonstaT** [comment]
@ric96 It does, just needs some hacking.

**Comment by peyo-hd** [comment]
Applied following 3 commits to nougat branch.
Regarding remaining commits for partition table (including cache partition), need more time to think about it.

https://github.com/android-rpi/device_brcm_rpi3/pull/70/commits/9c4538432a17e726617bb4c37b1bc7ea0837e62f
https://github.com/android-rpi/device_brcm_rpi3/pull/70/commits/7d02c8c3fce280a26589c492588e8c8067a08b55
https://github.com/android-rpi/device_brcm_rpi3/pull/70/commits/1a0793c60a0193685eef401069c8e10e6d301a21

**Comment by KonstaT** [comment]
It's been years since cache partition has been used for anything in Android. Only recovery writes its logs to /cache but this device doesn't even have recovery.

/cache still exist after this but it's now a symlink to data partition (/data/cache). Relevant commit here:
https://github.com/LineageOS/android_system_core/commit/c6535a343f0b0bdd0f4171f0b4c9be401beebf77

**Pull request closed without merging**
