### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ghost**
1. Add command to install gcc-arm-linux-gnueabihf
2. Fix mkfs.ex4 to mkfs.ext4

### CODE REVIEW

**Comment by ric96** [comment]
Afaik rpi kernel can have issues compiling with gcc crosscompiler from ubuntu repo

**Comment by ghost** [comment]
Yes, I have encountered it today, when I try to build android-rpi. I just modify Makefile to force set `stackp-flag := $(call cc-option, -fno-stack-protector)`, which can help me to avoid errors of ubuntu gcc-arm-linux-gnueabihf. My changes is below:

```git
diff --git a/Makefile b/Makefile
index 1099371..d38b47d 100644
--- a/Makefile
+++ b/Makefile
@@ -664,24 +664,24 @@ endif
 # to let the build fail with bad compiler flags so that we can't produce a
 # kernel when there is a CONFIG and compiler mismatch.
 #
-ifdef CONFIG_CC_STACKPROTECTOR_REGULAR
-  stackp-flag := -fstack-protector
-  ifeq ($(call cc-option, $(stackp-flag)),)
-    $(warning Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: \
-             -fstack-protector not supported by compiler)
-  endif
-else
-ifdef CONFIG_CC_STACKPROTECTOR_STRONG
-  stackp-flag := -fstack-protector-strong
-  ifeq ($(call cc-option, $(stackp-flag)),)
-    $(warning Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: \
-             -fstack-protector-strong not supported by compiler)
-  endif
-else
+#ifdef CONFIG_CC_STACKPROTECTOR_REGULAR
+#  stackp-flag := -fstack-protector
+#  ifeq ($(call cc-option, $(stackp-flag)),)
+#    $(warning Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: \
+#             -fstack-protector not supported by compiler)
+#  endif
+#else
+#ifdef CONFIG_CC_STACKPROTECTOR_STRONG
+#  stackp-flag := -fstack-protector-strong
+#  ifeq ($(call cc-option, $(stackp-flag)),)
+#    $(warning Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: \
+#            -fstack-protector-strong not supported by compiler)
+#  endif
+#else
   # Force off for distro compilers that enable stack protector by default.
   stackp-flag := $(call cc-option, -fno-stack-protector)
-endif
-endif
+#endif
+#endif
 KBUILD_CFLAGS += $(stackp-flag)

 ifeq ($(cc-name),clang)

```

The gcc-arm-linux-gnueabihf of ubuntu repo which I downloaded does not support option `-fstack-protector-strong`. I have tried to install gcc-5-arm-linux-gnueabihf , but it does not support my ubuntu version 14.04. So I use this method to avoid it.

**Comment by ghost** [comment]
@ric96 I have tested it with gcc-5-arm-linux-gnueabihf in my laptop with ubuntu 16.04 LTS, which works fine.

**Comment by peyo-hd** [comment]
Merged : Fix mkfs.ex4 to mkfs.ext4

Regarding this : Add command to install gcc-arm-linux-gnueabihf
 Package install command seems different between Linux distributions... so just keep simple direction only.

**Comment by ghost** [comment]
Thanks @peyo-hd

**Pull request closed without merging**
